---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: consul-test
  name: consul-test
  namespace: prod
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: consul-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: consul-test
    spec:
      containers:
        - env:
            - name: CONSUL_HTTP_ADDR
              value: http://consul-test-consul-server.prod.svc.cluster.local:8500
          image: viniciusramosdefaria/consul-test:latest
          imagePullPolicy: Always
          name: consul-test
          resources:
            limits:
              cpu: "1"
              memory: 1536Mi
            requests:
              cpu: 128m
              memory: 256Mi
          securityContext: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      terminationGracePeriodSeconds: 30